parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     symblog
    database_user:     root
    database_password: rivergod

    mailer_transport:  gmail
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host:       smtp.gmail.com
    mailer_user:       shibly.phy@gmail.com
    mailer_password:   user_pass

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
