blogger_blog_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method: GET

blogger_blog_about:
    pattern:  /about
    defaults: { _controller:BloggerBlogBundle:Page:about }
    requirements:
        _method: GET
